on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - _posts/**

jobs:
  generate_giscus_discussion:
    name: Generate a GitHub Discussion post for Giscus comments on the latest post
    runs-on: ubuntu-latest
    permissions:
      discussions: write
      contents: read
    steps:
      - env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          cargo install rss_autogen_giscus
      - name: Wait for site build to complete
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: main
          check-name: "deploy"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - env:
          # Link to the RSS feed that gets updated with the latest posts
          WEBSITE_RSS_URL: https://team-role-org-testing.github.io/feed.xml
          # Name of the category on GitHub discussions that the post should be made under
          DISCUSSION_CATEGORY: Blogs
          # The number of days to look backwards, checking if the post already exists. Limit is disabled if set to 0.
          #LOOKBACK_DAYS: 7
          # PAT for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rss_autogen_giscus
